[tool.poetry]
name = "superhero-api"
version = "0.1.0"
description = ""
authors = ["diglander <denisovchinn2094@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
response = "^0.5.0"
requests = "^2.33.1"
pytest = "^9.0.3"
responses = "^0.26.0"


[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
isort = "^8.0.1"
ruff = "^0.15.12"
mypy = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
